import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/meal_plan.dart';
import '../state/app_state.dart';
import '../widgets/auto_generate_dialog.dart';
import '../widgets/day_nutrition_summary_card.dart';
import 'meal_plan_screen.dart';

/// Reached by tapping a day in the calendar view: see/create/edit/delete that day's meals, plus
/// generate/regenerate the whole day's plan and see how the combined nutrition compares to targets.
class DayMealPlanScreen extends StatefulWidget {
  final DateTime date;
  const DayMealPlanScreen({super.key, required this.date});

  @override
  State<DayMealPlanScreen> createState() => _DayMealPlanScreenState();
}

class _DayMealPlanScreenState extends State<DayMealPlanScreen> {
  bool _loaded = false;
  bool _generating = false;
  DayNutritionSummary? _summary;
  String? _summaryKey;
  final Set<String> _selectedMealTypes = {};

  @override
  Widget build(BuildContext context) {
    final appState = context.watch<AppState>();
    if (!_loaded) {
      _loaded = true;
      final monthStart = DateTime(widget.date.year, widget.date.month, 1);
      final monthEnd = DateTime(widget.date.year, widget.date.month + 1, 0);
      final s = context.read<AppState>();
      Future.microtask(() => s.loadMealPlans(monthStart, monthEnd));
    }

    final dateStr = formatMealPlanDate(widget.date);
    final dayPlans = appState.mealPlans.where((m) => m.date == dateStr).toList();

    // Refetch the nutrition summary whenever this day's meal plans actually change (initial load,
    // an assign/delete/confirm-cooked action, or a regenerate) rather than on every rebuild.
    final summaryKey = dayPlans.map((m) => '${m.id}:${m.cooked}').join(',');
    if (summaryKey != _summaryKey) {
      _summaryKey = summaryKey;
      Future.microtask(_loadSummary);
    }

    return Scaffold(
      appBar: AppBar(
        title: Text(weekdayLabel(widget.date)),
        actions: [
          IconButton(
            icon: _generating
                ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2))
                : const Icon(Icons.auto_awesome),
            tooltip: _selectedMealTypes.isNotEmpty
                ? 'Generate for selected meals'
                : (dayPlans.isEmpty ? 'Generate plan for this day' : 'Regenerate plan for this day'),
            onPressed: _generating ? null : () => _generateForDay(context),
          ),
        ],
      ),
      body: ListView(
        children: [
          if (_selectedMealTypes.isNotEmpty)
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
              child: Row(
                children: [
                  Expanded(child: Text('${_selectedMealTypes.length} meal(s) selected', style: const TextStyle(fontWeight: FontWeight.w500))),
                  TextButton(onPressed: () => setState(_selectedMealTypes.clear), child: const Text('Clear')),
                ],
              ),
            ),
          if (_summary != null) DayNutritionSummaryCard(summary: _summary!),
          for (final mealType in mealTypes)
            MealSlot(
              day: widget.date,
              mealType: mealType,
              mealPlan: _findByMealType(dayPlans, mealType),
              selected: _selectedMealTypes.contains(mealType),
              onLongPress: (mt) => setState(() {
                if (_selectedMealTypes.contains(mt)) {
                  _selectedMealTypes.remove(mt);
                } else {
                  _selectedMealTypes.add(mt);
                }
              }),
            ),
        ],
      ),
    );
  }

  Future<void> _loadSummary() async {
    final summary = await context.read<AppState>().getDayNutritionSummary(widget.date);
    if (!mounted) return;
    setState(() => _summary = summary);
  }

  Future<void> _generateForDay(BuildContext context) async {
    final hasSelection = _selectedMealTypes.isNotEmpty;
    final options = await showAutoGenerateDialog(
      context,
      description: hasSelection
          ? 'Generates a plan for ${_selectedMealTypes.length} selected meal(s) on ${weekdayLabel(widget.date)}.'
          : 'Generates a plan for ${weekdayLabel(widget.date)}.',
      initialRegenerate: true,
      showMealTypeSelector: !hasSelection,
      preselectedMealTypes: hasSelection ? _selectedMealTypes.toList() : null,
    );
    if (options == null || !context.mounted) return;

    setState(() => _generating = true);
    final appState = context.read<AppState>();
    final ok = await appState.autoGenerateSchedule(
      from: widget.date,
      to: widget.date,
      mealTypes: options.mealTypes,
      stockFilter: options.stockFilter,
      avoidRepeatDays: options.avoidRepeatDays,
      targetNutrition: options.targetNutrition,
      regenerate: options.regenerate,
    );
    if (!context.mounted) return;
    setState(() {
      _generating = false;
      _selectedMealTypes.clear();
    });
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(ok ? 'Plan generated for this day.' : 'Could not generate a plan for this day.')),
    );
  }

  MealPlan? _findByMealType(List<MealPlan> plans, String mealType) {
    for (final p in plans) {
      if (p.mealType == mealType) return p;
    }
    return null;
  }
}
