import 'package:flutter/material.dart';
import '../models/meal_plan.dart';

class AutoGenerateOptions {
  final List<String> mealTypes;
  final String stockFilter;
  final int avoidRepeatDays;
  final bool targetNutrition;
  final bool regenerate;
  final int? days;

  AutoGenerateOptions({
    required this.mealTypes,
    required this.stockFilter,
    required this.avoidRepeatDays,
    required this.targetNutrition,
    required this.regenerate,
    this.days,
  });
}

/// Shared "auto-fill schedule" options dialog -- used by the calendar view (a day-count field plus
/// meal-type picker), the "Today's meals" list view and the day-detail page's generate button (a
/// single day, no day-count field), and all three when a meal/day selection is active elsewhere in
/// the screen (skips the meal-type picker and uses [preselectedMealTypes] as-is). Returns null if
/// cancelled.
Future<AutoGenerateOptions?> showAutoGenerateDialog(
  BuildContext context, {
  required String description,
  bool initialRegenerate = false,
  bool showMealTypeSelector = true,
  List<String>? preselectedMealTypes,
  bool showDaysField = false,
  int initialDays = 14,
}) async {
  final selectedMealTypes = {...(preselectedMealTypes ?? mealTypes)};
  String stockFilter = 'NONE';
  final avoidRepeatController = TextEditingController(text: '7');
  final daysController = TextEditingController(text: '$initialDays');
  bool targetNutrition = false;
  bool regenerate = initialRegenerate;

  final confirmed = await showDialog<bool>(
    context: context,
    builder: (dialogContext) => StatefulBuilder(
      builder: (dialogContext, setState) => AlertDialog(
        title: const Text('Auto-fill schedule'),
        content: SizedBox(
          width: double.maxFinite,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(description),
                const SizedBox(height: 12),
                if (showDaysField) ...[
                  TextField(
                    controller: daysController,
                    decoration: const InputDecoration(labelText: 'Number of days to fill'),
                    keyboardType: TextInputType.number,
                  ),
                  const SizedBox(height: 12),
                ],
                if (showMealTypeSelector) ...[
                  const Text('Meal types'),
                  Wrap(
                    spacing: 8,
                    children: mealTypes
                        .map((t) => FilterChip(
                              label: Text(t),
                              selected: selectedMealTypes.contains(t),
                              onSelected: (v) => setState(() => v ? selectedMealTypes.add(t) : selectedMealTypes.remove(t)),
                            ))
                        .toList(),
                  ),
                  const SizedBox(height: 12),
                ],
                const Text('Stock preference'),
                const SizedBox(height: 4),
                SegmentedButton<String>(
                  showSelectedIcon: false,
                  segments: const [
                    ButtonSegment(value: 'NONE', label: Text('Any')),
                    ButtonSegment(value: 'PRIORITIZE', label: Text('Stock first')),
                    ButtonSegment(value: 'ONLY_STOCK', label: Text('In stock')),
                  ],
                  selected: {stockFilter},
                  onSelectionChanged: (s) => setState(() => stockFilter = s.first),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: avoidRepeatController,
                  decoration: const InputDecoration(labelText: 'Avoid repeats within (days)'),
                  keyboardType: TextInputType.number,
                ),
                SwitchListTile(
                  contentPadding: EdgeInsets.zero,
                  title: const Text('Target my nutrition'),
                  subtitle: const Text('Picks recipes to fit your daily calorie/macro targets, set in Preferences.'),
                  value: targetNutrition,
                  onChanged: (v) => setState(() => targetNutrition = v),
                ),
                SwitchListTile(
                  contentPadding: EdgeInsets.zero,
                  title: const Text('Replace existing meals'),
                  subtitle: const Text('Off: only fills empty slots. On: also regenerates meals already planned.'),
                  value: regenerate,
                  onChanged: (v) => setState(() => regenerate = v),
                ),
              ],
            ),
          ),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(dialogContext, false), child: const Text('Cancel')),
          FilledButton(
            onPressed: selectedMealTypes.isEmpty ? null : () => Navigator.pop(dialogContext, true),
            child: const Text('Generate'),
          ),
        ],
      ),
    ),
  );
  if (confirmed != true) return null;

  return AutoGenerateOptions(
    mealTypes: selectedMealTypes.toList(),
    stockFilter: stockFilter,
    avoidRepeatDays: int.tryParse(avoidRepeatController.text) ?? 7,
    targetNutrition: targetNutrition,
    regenerate: regenerate,
    days: showDaysField ? (int.tryParse(daysController.text) ?? initialDays) : null,
  );
}
